apiVersion: apps/v1
kind: Deployment
metadata:
  name: colorteller
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: colorteller
  template:
    metadata:
      labels:
        app: colorteller
        version: blue
        group: control
    spec:
      nodeSelector:
        statsig.com/nodeType: spot
      containers:
      - name: colorteller
        image: gcr.io/statsig-services/demo-colorteller:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: STATSIG_SERVER_SDK_KEY
          value: "secret-g0JoYZRxKmo03eeQCJFGBGbEZ7ebU7D5CIFdJAlgsI8"
        - name: EXPERIMENT
          value: "colorapp"
        - name: GROUP
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['group']
        - name: COLOR
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['version']
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: colorteller-green
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: colorteller
  template:
    metadata:
      labels:
        app: colorteller
        version: green
        group: test
    spec:
      nodeSelector:
        statsig.com/nodeType: spot
      containers:
      - name: colorteller
        image: gcr.io/statsig-services/demo-colorteller:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: COLOR
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['version']
        - name: GROUP
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['group']
        - name: SERVER_PORT
          value: "8080"
        - name: STATSIG_SERVER_SDK_KEY
          value: "secret-g0JoYZRxKmo03eeQCJFGBGbEZ7ebU7D5CIFdJAlgsI8"
        - name: EXPERIMENT
          value: "colorapp"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
