apiVersion: v1
kind: Service
metadata:
  name: colorteller
  namespace: default
spec:
  selector:
    app: colorteller
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
